// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genre                string   `protobuf:"bytes,4,opt,name=genre,proto3" json:"genre,omitempty"`
	Edition              string   `protobuf:"bytes,5,opt,name=edition,proto3" json:"edition,omitempty"`
	NumberOfPages        int32    `protobuf:"varint,6,opt,name=numberOfPages,proto3" json:"numberOfPages,omitempty"`
	Year                 int32    `protobuf:"varint,7,opt,name=year,proto3" json:"year,omitempty"`
	Amount               int32    `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	IsPopular            bool     `protobuf:"varint,9,opt,name=isPopular,proto3" json:"isPopular,omitempty"`
	InStock              bool     `protobuf:"varint,10,opt,name=inStock,proto3" json:"inStock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetGenre() string {
	if m != nil {
		return m.Genre
	}
	return ""
}

func (m *Book) GetEdition() string {
	if m != nil {
		return m.Edition
	}
	return ""
}

func (m *Book) GetNumberOfPages() int32 {
	if m != nil {
		return m.NumberOfPages
	}
	return 0
}

func (m *Book) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Book) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Book) GetIsPopular() bool {
	if m != nil {
		return m.IsPopular
	}
	return false
}

func (m *Book) GetInStock() bool {
	if m != nil {
		return m.InStock
	}
	return false
}

type AddRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{7}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type ListingResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListingResponse) Reset()         { *m = ListingResponse{} }
func (m *ListingResponse) String() string { return proto.CompactTextString(m) }
func (*ListingResponse) ProtoMessage()    {}
func (*ListingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{8}
}

func (m *ListingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListingResponse.Unmarshal(m, b)
}
func (m *ListingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListingResponse.Marshal(b, m, deterministic)
}
func (m *ListingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListingResponse.Merge(m, src)
}
func (m *ListingResponse) XXX_Size() int {
	return xxx_messageInfo_ListingResponse.Size(m)
}
func (m *ListingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListingResponse proto.InternalMessageInfo

func (m *ListingResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "protocol.Book")
	proto.RegisterType((*AddRequest)(nil), "protocol.AddRequest")
	proto.RegisterType((*EmptyResponse)(nil), "protocol.EmptyResponse")
	proto.RegisterType((*DeleteRequest)(nil), "protocol.DeleteRequest")
	proto.RegisterType((*UpdateRequest)(nil), "protocol.UpdateRequest")
	proto.RegisterType((*GetRequest)(nil), "protocol.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "protocol.GetResponse")
	proto.RegisterType((*EmptyRequest)(nil), "protocol.EmptyRequest")
	proto.RegisterType((*ListingResponse)(nil), "protocol.ListingResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0xc9, 0xdf, 0x36, 0xb7, 0xa6, 0x0b, 0xc3, 0xba, 0x8e, 0xcb, 0x82, 0x21, 0xec, 0x43,
	0x9f, 0x8a, 0xb6, 0x82, 0x20, 0x7d, 0xa9, 0x28, 0x7d, 0x11, 0x2c, 0x29, 0x7e, 0x80, 0xb4, 0x73,
	0xad, 0x43, 0xd3, 0x4c, 0x4c, 0x26, 0x42, 0x3f, 0xb3, 0xdf, 0x41, 0x24, 0x33, 0x89, 0x69, 0xaa,
	0x59, 0xfa, 0x94, 0x9c, 0x73, 0xef, 0x3d, 0x39, 0xf9, 0x01, 0x6c, 0x85, 0x38, 0x4c, 0xb3, 0x5c,
	0x48, 0x41, 0x86, 0xea, 0xb1, 0x13, 0x49, 0xf8, 0xdb, 0x00, 0xfb, 0x83, 0x10, 0x07, 0x32, 0x06,
	0x93, 0x33, 0x6a, 0x04, 0xc6, 0xc4, 0x8b, 0x4c, 0xce, 0xc8, 0x2d, 0x38, 0x92, 0xcb, 0x04, 0xa9,
	0xa9, 0x2c, 0x2d, 0xc8, 0x1d, 0xb8, 0x71, 0x29, 0xbf, 0x8b, 0x9c, 0x5a, 0xca, 0xae, 0x55, 0xb5,
	0xbd, 0xc7, 0x34, 0x47, 0x6a, 0xeb, 0x6d, 0x25, 0x08, 0x85, 0x01, 0x32, 0x2e, 0xb9, 0x48, 0xa9,
	0xa3, 0xfc, 0x46, 0x92, 0x47, 0xf0, 0xd3, 0xf2, 0xb8, 0xc5, 0xfc, 0xcb, 0xb7, 0x75, 0xbc, 0xc7,
	0x82, 0xba, 0x81, 0x31, 0x71, 0xa2, 0xae, 0x49, 0x08, 0xd8, 0x27, 0x8c, 0x73, 0x3a, 0x50, 0x43,
	0xf5, 0xae, 0x1a, 0x1c, 0x45, 0x99, 0x4a, 0x3a, 0x54, 0x6e, 0xad, 0xc8, 0x03, 0x78, 0xbc, 0x58,
	0x8b, 0xac, 0x4c, 0xe2, 0x9c, 0x7a, 0x81, 0x31, 0x19, 0x46, 0xad, 0x51, 0x35, 0xe1, 0xe9, 0x46,
	0x8a, 0xdd, 0x81, 0x82, 0x9a, 0x35, 0x32, 0x7c, 0x0d, 0xb0, 0x64, 0x2c, 0xc2, 0x1f, 0x25, 0x16,
	0x92, 0x84, 0x60, 0x57, 0x98, 0x14, 0x87, 0xd1, 0x6c, 0x3c, 0x6d, 0x38, 0x4d, 0x2b, 0x46, 0x91,
	0x9a, 0x85, 0x37, 0xe0, 0x7f, 0x3a, 0x66, 0xf2, 0x14, 0x61, 0x91, 0x89, 0xb4, 0xc0, 0xf0, 0x15,
	0xf8, 0x1f, 0x31, 0x41, 0x89, 0x4d, 0xca, 0x05, 0xcb, 0x70, 0x0e, 0xfe, 0xd7, 0x8c, 0xc5, 0xed,
	0xc2, 0x35, 0x9f, 0x79, 0x00, 0x58, 0xa1, 0xec, 0x8b, 0x7c, 0x03, 0x23, 0x35, 0xd5, 0x15, 0xae,
	0x0a, 0x1c, 0xc3, 0xb3, 0xba, 0xb7, 0x8a, 0x0c, 0xdf, 0xc1, 0xcd, 0x67, 0x5e, 0x48, 0x9e, 0xee,
	0xff, 0xc6, 0x3c, 0x82, 0x53, 0xad, 0x16, 0xd4, 0x08, 0xac, 0xff, 0xe4, 0xe8, 0xe1, 0xec, 0x97,
	0x09, 0xa3, 0x4a, 0x6f, 0x30, 0xff, 0xc9, 0x77, 0x48, 0xde, 0x82, 0xb5, 0x64, 0x8c, 0xdc, 0xb6,
	0xdb, 0x2d, 0xd1, 0xfb, 0x17, 0xad, 0xdb, 0xa1, 0x46, 0xde, 0x83, 0xab, 0xa9, 0x91, 0xb3, 0x95,
	0x0e, 0xc7, 0x27, 0x6f, 0x35, 0xd0, 0xf3, 0xdb, 0x0e, 0xe2, 0xfe, 0xdb, 0x19, 0x58, 0x2b, 0x94,
	0xe7, 0x6d, 0x5b, 0xcc, 0xf7, 0xcf, 0x2f, 0xdc, 0xfa, 0x66, 0x01, 0x83, 0x1a, 0x15, 0xb9, 0xfb,
	0x27, 0x57, 0x5f, 0xbe, 0x6c, 0xfd, 0x4b, 0xaa, 0x0b, 0xf0, 0xf4, 0x7f, 0x2d, 0x93, 0xa4, 0xf7,
	0xbe, 0xaf, 0xef, 0xd6, 0x55, 0xfe, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xf6, 0x67,
	0x55, 0xc0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Listing(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListingResponse, error)
	DeleteAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Listing(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListingResponse, error) {
	out := new(ListingResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/Listing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteAll(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.BookService/DeleteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	Add(context.Context, *AddRequest) (*EmptyResponse, error)
	Delete(context.Context, *DeleteRequest) (*EmptyResponse, error)
	Update(context.Context, *UpdateRequest) (*EmptyResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Listing(context.Context, *EmptyRequest) (*ListingResponse, error)
	DeleteAll(context.Context, *EmptyRequest) (*EmptyResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) Add(ctx context.Context, req *AddRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedBookServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedBookServiceServer) Update(ctx context.Context, req *UpdateRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBookServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBookServiceServer) Listing(ctx context.Context, req *EmptyRequest) (*ListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listing not implemented")
}
func (*UnimplementedBookServiceServer) DeleteAll(ctx context.Context, req *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAll not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Listing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Listing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/Listing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Listing(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.BookService/DeleteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteAll(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BookService_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BookService_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BookService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BookService_Get_Handler,
		},
		{
			MethodName: "Listing",
			Handler:    _BookService_Listing_Handler,
		},
		{
			MethodName: "DeleteAll",
			Handler:    _BookService_DeleteAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
